#!/usr/bin/env bash

# Include files
. src/definitions

# Trap ctr-c
trap exitAll SIGINT

# init the log file
initLog

# run pre-start setup
preStart
[ $# = 0 ] && { printUsage; exit; } || parseArgs "$@"