#!/usr/bin/env bash

# Clear the terminal
tput clear

# Include files
. src/definitions

# Trap ctr-c
trap exitAll SIGINT
 
# Check privileges
if ! isSudo; then 
        logPrint "ERR" "Please run the following command instead!" "sudo $0" "${FAIL}"
fi

[ $# = 0 ] && { printUsage; exit; } || parseArgs "$@" 

