#!/bin/bash

# Get OS and Version
# Return OS, Version and the Architecture
function getOSInfo(){
	# Init output variables 
	local  __res_os=$1
	local  __res_ver=$2
	local  __res_arch=$3

	local __OS
	local __VER
	local __ARCH

	if [ -f /etc/os-release ]; then
		. /etc/os-release
		__OS=$NAME
		__VER=$VERSION_ID
	elif [ -f /etc/lsb-release ]; then
		. /etc/lsb-release
	        __OS=$DISTRIB_ID
		__VER=$DISTRIB_RELEASE
	else
		__OS=$(uname -s)
		__VER=$(uname -r)
	fi

	# Get OS Architecture
	if [ $(uname -m) == 'x86_64' ]; then
		__ARCH=x64
	else
		__ARCH=x86
	fi

	eval $__res_os="'$__OS'"
	eval $__res_ver="'$__VER'"
	eval $__res_arch="'$__ARCH'"
}
