#!/usr/bin/env bash

# Include files
SRC="${BASH_SOURCE%/*}"
if [ ! -d "$SRC" ]; then SRC="$PWD"; fi

. $SRC/cmd
. $SRC/format
. $SRC/functions
. $SRC/update_kernel

# Requirement
REQ_BASH_VERSION=4.3


# DIRECTORY Paths
TEMP_DIRECTRORY=$(mktemp -d)
WORK_DIRECTRORY="./benchmarks"
LOG_DIRECTRORY="./log"

# File Paths
REQ_FILE="requirements/req.yml"
DEF_FILE="src/definitions"
LOG_FILE="${LOG_DIRECTRORY}/ret.log"

# Url's
UBUNTU_KERNEL_URL=kernel.ubuntu.com/~kernel-ppa/mainline/
TF_BENCHMARKS_URL="https://github.com/tensorflow/benchmarks.git"

# Scop
EMPTY_ARRAY=()
VERSION="0.1.x"
DESCRIPTION="ROCm Machine Learning Stack installer"
TF_BNCH_VER="cnn_tf_v1.13_compatible"
TF_MODEL="resnet50"
NUM_GPUS=1
BATCH_SIZE=128

# Run-time params
TOTALSTEPS=12
BEQUIET=false
PYVER="py3"
[ "$PYVER" = "py2" ] && PYPI="pip" || PYPI="pip3"

# Commands
# Debian cmds
DEB_INSTALL_CMD="apt-get -qq -y --allow-unauthenticated install"
DEB_REMOVE_CMD="apt-get autoremove -qq -y"
DEB_UPDATE_CMD="apt-get update"
DEB_SEARCH_CMD="dpkg -l"
DEB_FIXBROKEN_CMD="apt-get install -fqq"
DEB_CLEAN_CMD="apt-get clean"

# CentOS cmds
COS_INSTALL_CMD="apt-get -qq -y --allow-unauthenticated install"
COS_REMOVE_CMD="apt-get autoremove -qq -y"
COS_UPDATE_CMD="apt-get update"
COS_SEARCH_CMD="dpkg -l"
COS_FIXBROKEN_CMD="apt-get install -fqq"
COS_CLEAN_CMD="apt-get clean"