#!/usr/bin/env bash

# Include files
PWD=$(pwd)
SRC="${BASH_SOURCE%/*}"
if [ ! -d "$SRC" ]; then SRC="$PWD"; fi

. $SRC/cmd
. $SRC/format
. $SRC/functions
. $SRC/update_kernel

# Requirement
REQ_BASH_VERSION=4.3


# DIRECTORY Paths
TEMP_DIRECTRORY=$(mktemp -d)
WORK_DIRECTRORY="./benchmarks"
LOG_DIRECTRORY="./log"

# File Paths
REQ_FILE="requirements/req.yml"
DEF_FILE="src/definitions"
LOG_FILE="${LOG_DIRECTRORY}/ret.log"
BASH_FILENAME="bash-4.4.18"
Ubuntu_ROCM_REPO="/etc/apt/sources.list.d/rocm.list"
CentOS_ROCM_REPO="/etc/yum.repos.d/rocm.repo"

# Url's
UBUNTU_KERNEL_URL="kernel.ubuntu.com/~kernel-ppa/mainline/"
TF_BENCHMARKS_URL="https://github.com/tensorflow/benchmarks.git"
BASH_URL="https://ftp.gnu.org/gnu/bash/"
ROCM_DEB="http://repo.radeon.com/rocm/apt/debian/ xenial main"
ROCM_RPM="http://repo.radeon.com/rocm/yum/rpm"

# Scope
EMPTY_ARRAY=()
RET_VERSION="0.1.x"
DESCRIPTION="ROCm Machine Learning Stack installer"

# Benchmark
TF_BNCH_VER="cnn_tf_v1.13_compatible"
TF_MODEL="resnet50"
NUM_GPUS=1
BATCH_SIZE=128

# Run-time params
TOTALSTEPS=12
BEQUIET=false
FORCEYES=false
PYVER="py3"
[ "$PYVER" = "py2" ] && PYPI="pip" || PYPI="pip3"

# Debian cmds
DEB_INSTALL_CMD="apt-get -qq -y --allow-unauthenticated install"
DEB_INSTALL_PKG_CMD="dpkg -i"
DEB_REMOVE_CMD="apt-get autoremove -qq -y"
DEB_UPDATE_CMD="apt-get update"
DEB_SEARCH_CMD="dpkg -l"
DEB_FIXBROKEN_CMD="apt-get install -fqq"
DEB_CLEAN_CMD="apt-get clean"

# CentOS cmds
COS_INSTALL_CMD="yum -q -y install"
COS_INSTALL_PKG_CMD="rpm -i"
COS_REMOVE_CMD="yum autoremove -q -y"
COS_UPDATE_CMD="yum check-update"
COS_SEARCH_CMD="yum list installed"
COS_FIXBROKEN_CMD="$RET_IGNORE_CMD"
COS_CLEAN_CMD="yum clean packages"

# Commands
RET_IGNORE_CMD="ret_ignore"
RET_INSTALL_CMD=0
RET_INSTALL_PKG_CMD=1
RET_REMOVE_CMD=2
RET_UPDATE_CMD=3
RET_SEARCH_CMD=4
RET_FIXBROKEN_CMD=5
RET_CLEAN_CMD=6

# Init commands array with debian cmds
RET_CMDS_ARRAY=("DEB_INSTALL_CMD" "DEB_INSTALL_PKG_CMD" "DEB_REMOVE_CMD" "DEB_UPDATE_CMD" "DEB_SEARCH_CMD" "DEB_FIXBROKEN_CMD" "DEB_CLEAN_CMD")
