#!/usr/bin/env bash

# Format
BOLD='\e[1m'
DIM='\e[2m'
UNDERLINED='\e[4m'
REVERSE='\e[7m'
HIDDEN='\e[8m'
END='\e[0m'

# Colors Foreground
FG_DEFAULT='\e[39m'
FG_BLACK='\e[30m'
FG_RED='\e[31m'
FG_GREEN='\e[32m'
FG_YELLOW='\e[33m'
FG_BLUE='\e[34m'
FG_MAGENTA='\e[35m'
FG_CYAN='\e[36m'
FG_LIGHT_GRAY='\e[37m'
FG_DARK_GRAY='\e[90m'
FG_LIGHT_RED='\e[91m'
FG_LIGHT_GREEN='\e[92m'
FG_LIGHT_YELLOW='\e[93m'
FG_LIGHT_BLUE='\e[94m'
FG_LIGHT_MAGENTA='\e[95m'
FG_LIGHT_CYAN='\e[96m'
FG_WHITE='\e[97m'
FG_ORANGE='\e[38;5;208m'

# Colors Background
BG_DEFAULT='\e[49m'
BG_BLACK='\e[40m'
BG_RED='\e[41m'
BG_GREEN='\e[42m'
BG_YELLOW='\e[43m'
BG_BLUE='\e[44m'
BG_MAGENTA='\e[45m'
BG_CYAN='\e[46m'
BG_LIGHT_GRAY='\e[47m'
BG_DARK_GRAY='\e[100m'
BG_LIGHT_RED='\e[101m'
BG_LIGHT_GREEN='\e[102m'
BG_LIGHT_YELLOW='\e[103m'
BG_LIGHT_BLUE='\e[104m'
BG_LIGHT_MAGENTA='\e[105m'
BG_LIGHT_CYAN='\e[106m'
BG_WHITE='\e[107m'

# Custom format
SUCC="${FG_GREEN}✔ "
FAIL="${FG_RED}✘ "
ERR="${FG_RED}✘ [ERROR] "
WARN="${FG_ORANGE}[WARNING] "
STEP="${BOLD}${FG_CYAN}[+] "
NOTE="${BOLD}${BG_DARK_GRAY}[INFO] "

